--PARAMETRIZACIÓN INICIAL

BEGIN
--INSERT PROVEEDORES
INSERT INTO PROVEEDORES (NOMBRE, CIF, TELEFONO, EMAIL) VALUES ('Césped SA', 'B52145978', 651459784, 'cespedsa@mail.com');
INSERT INTO PROVEEDORES (NOMBRE, CIF, TELEFONO, EMAIL) VALUES ('Inter Césped', 'B59878964', 699699966, 'intercesped@mail.com');
INSERT INTO PROVEEDORES (NOMBRE, CIF, TELEFONO, EMAIL) VALUES ('Nuevo Césped', 'B55544965', 654321012, 'nuevocesped@mail.com');
INSERT INTO PROVEEDORES (NOMBRE, CIF, TELEFONO, EMAIL) VALUES ('Cespéd España', 'B59863597', 665544995, 'cespedespana@mail.com');

--INSERT PRODUCTOS
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, ID_PROVEEDOR) VALUES ('Olimpo 50', 12.5, 100, '2');
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, ID_PROVEEDOR) VALUES ('Pegasus 40', 10.5, 50, '2');
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, ID_PROVEEDOR) VALUES ('Aires 25', 8.9, 200.5, '1');
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, ID_PROVEEDOR) VALUES ('Top 50', 9.5, 45.5, '4');
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, ID_PROVEEDOR) VALUES ('Atlanta 30', 11.5, 100, '4');
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK, ID_PROVEEDOR) VALUES ('Atlas 50', 16.9, 125.5, '1');

--INSERT CLIENTES
INSERT INTO CLIENTES (NOMBRE, APELLIDOS, DNI, TELEFONO, EMAIL) VALUES ('José', 'Sanchéz Garcia', '74595864A', '612498759', 'jsc@mail.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDOS, DNI, TELEFONO, EMAIL) VALUES ('Maria', 'Perez Cubero', '16547895B', '697849587', 'mpc@mail.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDOS, DNI, TELEFONO, EMAIL) VALUES ('Manuel', 'Asenjo Millán', '63497861C', '634102587', 'mam@mail.com');
INSERT INTO CLIENTES (NOMBRE, APELLIDOS, DNI, TELEFONO, EMAIL) VALUES ('Anna', 'Mainar Gracia', '54978230D', '654987123', 'amg@mail.com');

INSERT INTO USUARIOS (NOMBRE, USERNAME, PASS, ROLE) VALUES ('Admin', 'Sfaci', '1234', 'admin');
INSERT INTO USUARIOS (NOMBRE, USERNAME, PASS, ROLE) VALUES ('Usuario', 'Usuario', '1234', 'usuario');
INSERT INTO USUARIOS (NOMBRE, USERNAME, PASS, ROLE) VALUES ('Joana', 'Jfreitas', '1234', 'admin');

COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;
